export const GET_DISCUSSION_DATA_BEGIN = 'GET_DISCUSSION_DATA_BEGIN'
export const GET_DISCUSSION_DATA_FAIL = 'GET_DISCUSSION_DATA_FAIL'
export const GET_DISCUSSION_DATA_SUCCESS = 'GET_DISCUSSION_DATA_SUCCESS'