export const SUBMIT_TRACKER_SURVEY_DATA_BEGIN = 'SUBMIT_TRACKER_SURVEY_DATA_BEGIN'
export const SUBMIT_TRACKER_SURVEY_DATA_FAIL = 'SUBMIT_TRACKER_SURVEY_DATA_FAIL'
export const SUBMIT_TRACKER_SURVEY_DATA_SUCCESS = 'SUBMIT_TRACKER_SURVEY_DATA_SUCCESS'

export const GET_TRACKER_SURVEY_DATA_BEGIN = 'GET_TRACKER_SURVEY_DATA_BEGIN'
export const GET_TRACKER_SURVEY_DATA_FAIL = 'GET_TRACKER_SURVEY_DATA_FAIL'
export const GET_TRACKER_SURVEY_DATA_SUCCESS = 'GET_TRACKER_SURVEY_DATA_SUCCESS'

export const TRACKER_LOADER_START = 'TRACKER_LOADER_START'
export const TRACKER_LOADER_END = 'TRACKER_LOADER_END'